src/App.tsx

Revert "pr테스트"

---

.husky/pre-commit
README.md
package-lock.json
package.json
src/api/activitiesApi.ts
src/api/authApi.ts
src/api/constants/url.ts
src/api/instance/defaultInstance.ts
src/api/types/activities.ts
src/api/types/auth.ts

[Feat] axios 인스턴스, 인터셉터 구현

---

src/api/instance/defaultInstance.ts
src/components/modal/useModal.scss
src/components/modal/useModal.tsx

- 모달 기능 구현
- instance에 있는 timeout 삭제 
- timeout 해당시간이 넘어가면 401에러가 나기전에  오류가 전송이 되어 토큰을 재할당 받지 못했음

[Feat] modal 구현, instance 수정

---

src/App.tsx
src/api/getMyInfo.ts
src/components/temp/index.tsx
src/components/temp/style.scss
src/pages/ActivityDetails/index.tsx
src/pages/Main/index.tsx
src/redux/myInfoSlice.ts
src/redux/store/store.ts

- 로그인 관련해서 리덕스 툴킷 필요한 슬라이스가 있어서 파일분리 했습니다
- 공간 어쩌구 다 롤백하고 작업한거라 현진님 PR이랑 부딪히는게 없을것 같습니다

[Chore] 임시로그인버튼 리팩터링

---

src/pages/Main/index.tsx
src/pages/SpaceDetails/index.tsx
src/routes/routes.tsx

- 폴더명, 파일명, 라우팅, 함수명 등 변경했습니다
- MySpaceManagement 아래 현진님이 만드신 파일명, 텍스트등은 제가 손댔다가 더 꼬일수도 있을것같아서 냅뒀습니다

[Docs] 체험 => 공간

---

src/api/instance/defaultInstance.ts
src/pages/AddSpace/index.tsx
src/pages/EditSpace/index.tsx
src/pages/Main/index.tsx
src/pages/MyPage/index.tsx
src/pages/MyReservation/index.tsx
src/routes/routes.tsx

- url 주소와 폴더이름을 수정했습니다
- instance에 timeout을 5초 주었습니다

[Rename] url주소 및 폴더이름 수정

---

public/assets/icons/icon-loading.svg
src/pages/Loading/style.scss

- 준용님이 말씀하신 디자인으로 변경했습니다!
- 예쁘게 봐주세요~~

[Design] 로딩페이지 디자인 변경

---

src/styles/_base.scss

- root에 캘린더에 들어가는 주요 색상들 추가 살짝 했습니다!
- 우리팀 재밌다

[Design] 공통 스타일 설정 변경

---

src/styles/_base.scss

- input에 font-family 설정 추가했습니다!
- 맛점 맛점

[Design] input에 기본 폰트 설정 추가

---

src/components/Button/types/buttonType.ts
src/pages/AddSpace/comnponents/CategoryDropdown/index.tsx
src/pages/AddSpace/comnponents/Schdules/DateInput/index.tsx
src/pages/AddSpace/comnponents/Schdules/index.tsx
src/pages/AddSpace/comnponents/Schdules/style.scss

#43
- 공통 컴포넌트 button extends 추가
- 내 공간 등록 페이지, 내 공간 수정 페이지 css 추가
- 화이팅

[Refactor] 버튼컴포넌트 extends 수정 및 내 공간 등록 css 추가

---

src/pages/AddSpace/comnponents/AddPlaceForm/index.tsx
src/pages/AddSpace/comnponents/PriceInput/index.tsx
src/pages/AddSpace/comnponents/Schdules/DateInput/index.tsx
src/pages/AddSpace/comnponents/Schdules/TimeDropdown/index.tsx
src/pages/AddSpace/comnponents/Schdules/index.tsx
src/pages/AddSpace/comnponents/Schdules/style.scss
src/pages/EditSpace/index.tsx
src/utils/compareTime.ts
src/utils/removeCommas.ts

#43
- AddSpace, EditSpace 필수 데이터를 입력하지 않으면 필요한 데이터를 알려주는 토스트가 표시되게 구현했습니다
- Schedule을 추가할 때 날짜가 없거나 시작시간이 끝나는 시간보다 빠르면 등록이 되지 않으며 해당 사항을 알려주는 토스트가 표시되게 구현했습니다
- Schedule 시간 선택에 드롭다운을 사용했으며 css추가했습니다
- 가격을 적는 input에 천 단위로 ,(쉼표)가 찍히게 만들었습니다
- 화이팅!

[Refactor]: AddSpace, EditSpace, Schedule 유효성 검사 기능 강화 및 기타 작업

---

src/hooks/useMyActivities/index.ts
src/pages/AddSpace/comnponents/AddPlaceForm/index.tsx
src/pages/AddSpace/comnponents/AddPlaceForm/style.scss
src/pages/EditSpace/index.tsx
src/pages/EditSpace/styles.scss
src/pages/MySpaceManagement/components/MySpaceCard/index.tsx
src/pages/MySpaceManagement/components/MySpaceCard/style.scss
src/pages/MySpaceManagement/components/MySpaceHeader/index.tsx
src/pages/MySpaceManagement/components/MySpaceHeader/style.scss
src/pages/MySpaceManagement/components/MySpaceList/index.tsx
src/pages/MySpaceManagement/index.tsx
src/pages/MySpaceManagement/style.scss
src/routes/mypagelayout/index.tsx

#76 
- 마이 페이지에 액세스토큰 및 리프래쉬토큰이 없으면 로그인 페이지로 리다이렉트하는 기능 구현
- 내 공간 관리 페이지 ui & 기능 분리
- 태그 및 css 약간 수정
- 화이팅!

[Feat] 마이페이지 리다이렉트 기능 및 기타 작업

---

src/api/activitiesApi.ts
src/api/instance/defaultInstance.ts

- instance에 multipart/form-data타입일 경우 헤드에 자동으로 부착되게 수정 
- application/json 값이 디폴트라서  multipart/form-data일 경우에는 일일이 api 헤더 부분에 수정을 했어야 했는데 이제 그럴 필요가 없어졌습니다!
- 화이팅!

[Refactor] instance에 multipart/form-data추가

---

src/pages/ReservationStatus/index.tsx
src/pages/ReservationStatus/style.scss

#25 
- 예약현황을 확인하는 id가 없을 때 예약현황 페이지에 들어갈 수 없는 버그 수정
- 예약 없을 때 예약 없음을 보여주는 화면 추가
- 아직 수정할 거 많지만 버그 먼저 고치려고 pr 올립니다 아자아자

[Fix] 예약현황 페이지에서 id가 없을 때 오류나는 버그 수정 및 예약이 없을 때 예약 없음을 보여주는 화면 추가

---

src/api/types/reservationStatus.d.ts
src/components/Calendar/components/ReservationInformation.tsx
src/pages/Loading/types/loadingType.ts

- type 오류 해결을 위한 옵셔널 추가
- 컴포넌트에 있던 타입을 본인이 있어야 할 자리로 이동시켰습니다.
- 모두에게 빨간 줄을 드리게 되어 아주 죄송함다 꾸벅 다들 아프지 망고 행복하세요

[Fix] type 오류 해결을 위한 옵셔널 추가 및 타입 폴더 이동

---

src/components/Footer/style.scss
src/components/Header/components/HeaderButtons.tsx
src/pages/Main/components/SpaceCardList.tsx
src/pages/Main/index.tsx

- 헤더 로그인 / 회원가입 Link 연결
- 푸터 마진 추가
- 메인페이지 불필요한 Link 삭제
- 검색 시 카테고리, 가격 정렬 드롭다운 숨기기
- 메인페이지에서 검색 시 '전체'가 아니라 검색어를 보여주게 수정해야 합니다!
- 전체적인 CSS는 예약 내역 페이지 완료 후 수정 예정
- 예약 내역 올리기 전에 수정사항 먼저 올립니다 'v' !!

[Fix] Header 버튼 수정 및 메인페이지 조건부 렌더링

---

public/assets/icons/icon-top.svg
src/api/reservationStatusApi.ts
src/components/Calendar/components/ReservationInformation.tsx
src/components/Calendar/components/reservationInformation.scss

#25 
- 예약 현황 모달 내 예약 내역이 업데이트 될 때마다 캐시를 초기화하도록 수정
- 예약 내역이 많아짐을 대비해 스크롤 기능과 아이콘 클릭 시 예약 내역 최상단으로 올라가는 기능 추가함
- 아직 고칠 부분이 많네요 내일은 오늘 회의 때 나온 부분들 수정해보겠습니다! 모두 행밤 🥰

[Fix] 예약 현황 모달 내 예약 내역이 업데이트 될 때마다 캐시를 초기화하도록 수정

---

src/components/MypageSidebar/components/MypageProfile.tsx
src/components/MypageSidebar/style.scss
src/pages/SpaceDetails/Components/DeleteModal/index.tsx
src/pages/SpaceDetails/Components/DeleteModal/style.scss

- 디자인을 좀 바꿔보았습니다
- 선영님의 모달도 곧... 커밍 쑨...
- 선영님 모달까지 올립니다!

[Design] 삭제 모달, 프로필 이미지 수정 모달 디자인 변경

---

src/api/postReservation.ts
src/pages/SignIn/index.tsx
src/pages/SpaceDetails/Components/CalendarContainer/index.tsx
src/pages/SpaceDetails/Components/CalendarContainer/style.scss
src/pages/SpaceDetails/Components/ToLoginModal/index.tsx
src/pages/SpaceDetails/Components/ToLoginModal/style.scss
src/pages/SpaceDetails/Types/DetailTypes.ts
src/pages/SpaceDetails/index.tsx
src/pages/SpaceDetails/style.scss

[Feat] 로그인 안했을때 예약하면 로그인화면으로 보내버리고 로그인 하면 다시 보던 페이지로

---

src/components/Footer/style.scss
src/components/MyNotifications/style.scss
src/components/Pagination/components/paginationButton.scss
src/pages/Main/components/HotSpaceCard/style.scss
src/pages/Main/components/HotSpaceCardList/index.tsx
src/pages/Main/components/HotSpaceCardList/style.scss

- 페이지네이션, 푸터, 알림 모달 수정했습니다!
- 인기공간 반응형 수정했습니다!
- 인기공간 반응형 수정을 하긴 했지만... 너무 맘에 안 들어서 아직 계속 수정 중입니다만 나머지 수정이랑 같이 먼저 올리겠습니다..ㅎㅎ
- 항 행 하~

[Design] 인기 공간, 페이지네이션, 푸터, 알림 모달 수정

---

src/pages/ReservationStatus/index.tsx
src/routes/routes.tsx

- npm run build 했을 때 뜨는 빌드 오류를 고치기 위해 빠른 수정!
- npm run build를 금세 까먹다니 죄송합니다 꾸벅 (__)

[Hotfix] 예약현황 페이지 내 컴포넌트 props 오류 수정

---

src/hooks/useModal/useModal.tsx
src/pages/AddSpace/components/AddPlaceForm/style.scss
src/pages/AddSpace/components/Schdules/style.scss
src/pages/EditSpace/styles.scss
src/pages/SpaceDetails/Components/CalendarContainer/index.tsx

- useModal 안의 Modal 컴포넌트가 리랜더링이 되지 않게 useCallback함수를 사용했습니다
- 화이팅

[Refactor] useModal 리팩토링

---

src/components/Calendar/components/calendarCells.scss
src/components/Calendar/components/calendarReservationChip.scss
src/components/Calendar/style.scss
src/components/Header/components/headerDropdown.scss
src/pages/ReservationStatus/style.scss
src/styles/_base.scss

- 예약현황 칩 디자인 수정
- 예약현황 페이지 내에 드롭다운과 캘린더에 padding 제거
- 선영님의 드롭다운 css 수정을 대신 해보았습니다
- 왜 벌써 9시 30분이 다 되어가죠...? 행밤 🌷

[Design] 예약현황 페이지 디자인 수정

---

src/pages/ReservationStatus/components/ReservationInformation.tsx
src/pages/ReservationStatus/components/reservationInformation.scss
src/styles/_base.scss

- 탭마다 색상이 달라지도록 수정했습니다!
- 졸리네요zzz

[Design] 예약현황 모달 내 디자인 수정

---

src/pages/AddSpace/components/ImageUploader/style.scss

- 내 공간 등록/수정 사진 업로드 미리보기 css 수정
- 흔쾌히 허락해주신 현진님에게 감사의 인사 전합니다🫡

[Design] 현진님의 이미지 업로드 컴포넌트 디자인 수정
